<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.Identity.Mongo" Version="10.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TheGuild.Infrastructure.MongoDb\TheGuild.Infrastructure.MongoDb.csproj" />
    </ItemGroup>

</Project>
